web:
        build: .
        command: python3 app.py --log=debug
        ports:
         - "8081:8081"
        links:
         - mongo
mongo:
        image: mongo
		volumes_from: [data]

data:
		image: mongo
		volumes: /data/db