# Site settings
title: Fishtank
email: fishtank.mahalogreens@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to fish tank, a remote controlled and monitored fishtank.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://renomania.ddns.net" # the base hostname & protocol for your site
twitter_username: freefood89
github_username:  freefood89

# Build settings
markdown: kramdown
